### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by Erquint** [ndrplz/google-drive-downloader#29]
```
PS C:\Users\Erquint\Downloads> pip install googledrivedownloader
Collecting googledrivedownloader
  Downloading googledrivedownloader-0.4-py2.py3-none-any.whl (3.9 kB)
Installing collected packages: googledrivedownloader
Successfully installed googledrivedownloader-0.4
WARNING: You are using pip version 21.2.3; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Python39\python.exe -m pip install --upgrade pip' command.
PS C:\Users\Erquint\Downloads> python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from google_drive_downloader import GoogleDriveDownloader as gdd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\google_drive_downloader\__init__.py", line 1, in <module>
    from .google_drive_downloader import GoogleDriveDownloader
  File "C:\Python39\lib\site-packages\google_drive_downloader\google_drive_downloader.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>
```

**Comment by ChristianKleineidam** [comment]
I had the same error.

**Comment by csetanmayjain** [comment]
Can you try: `pip install requests`

**Comment by Erquint** [comment]
Yeah, that works. But it should be taken care of by the package manager satisfying dependencies declared in the package, shouldn't it?
I opened the issue suspecting that the manifest lacks a declaration of that dependency. I'd suggest a fix if I was familiar with how that is to be declared.

**Comment by ndrplz** [comment]
This should be fixed now.
